/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* p2_2.c Toggle Green LED (LD2) on STM32F446RE Nucleo64 board at 1 Hz
 *
 * This program toggles LD2 for 0.5 second ON and 0.5 second OFF
 * by writing a '1' to bit 5 or bit 21 of the Bit Set/Reset
 * Register (BSRR). The lower 16 bits of BSRR turns on the pins
 * and the upper 16 bits of BSRR turns off the pins.
 * Writing a '1' to bit 5 turns on pin 5. Writing a '1' to
 * bit 21 (5 + 16) turns off pin 5.
 * The green LED (LD2) is connected to PA5.
 * The LED is high active (a '1' turns on the LED).
 * The default system clock is running at 16 MHz.
 *
 * This program was tested with Keil uVision v5.24a with DFP v2.11.0
 */

#include "stm32f4xx.h"
#include "stm32f429xx.h"

void delayMs(uint16_t n);

int delay_complete = 1;  // assume the delay is complete

int main(void) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;      // enable GPIOG clock 0x1UL << 6U

	GPIOG->MODER &= ~(GPIO_MODER_MODE14);    // 0x3UL << 28U
	GPIOG->MODER |=  GPIO_MODER_MODE14_0;    // set pin to output mode 0x1UL << 28U


    while(1) {
        GPIOG->BSRR = GPIO_BSRR_BS14;   // turn on LED 0x1UL << 14U
        delayMs(500);
        GPIOG->BSRR = GPIO_BSRR_BR14_Msk;   // turn off LED 0x1UL << 30U
        delayMs(500);
    }
}

/* 16 MHz SYSCLK */
void delayMs1(int n) {
    int i;
    for (; n > 0; n--)
        for (i = 0; i < 3195; i++) ;
}


void delayMs(uint16_t ms) {
    // Enable the TIM2 clock
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

    // Configure the TIM2 timer
    TIM2->PSC = (16000000/1000000)-1;  // Set the prescaler to achieve 1us resolution, assuming the system clock frequency is set to 16 MHz
    TIM2->ARR = ms * 1000;  // Set the auto-reload value to the desired delay in ms
    TIM2->CR1 |= TIM_CR1_ARPE;  // Enable auto-reload preload
    TIM2->CR1 &= ~TIM_CR1_DIR;  // Count up

    // Enable interrupt for TIM2 update event
    TIM2->DIER |= TIM_DIER_UIE;
    NVIC_EnableIRQ(TIM2_IRQn);

    // Start the TIM2 timer
    TIM2->CR1 |= TIM_CR1_CEN;

    // Wait for the TIM2 timer to complete the delay
    while (delay_complete == 0);

    // Disable the TIM2 timer
    TIM2->CR1 &= ~TIM_CR1_CEN;

    // Disable interrupt for TIM2 update event
    TIM2->DIER &= ~TIM_DIER_UIE;
    NVIC_DisableIRQ(TIM2_IRQn);

    delay_complete = 0;
}

void TIM2_IRQHandler(void) {
    // Clear the TIM2 timer interrupt flag
    TIM2->SR &= ~TIM_SR_UIF;

    // Set the flag to indicate that the delay has completed
    delay_complete = 1;
}

