/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include "stm32f4xx.h"

void delayMs(int n);

int main(void) {

    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;        // Enable GPIOG clock (0x1 << 6U)
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;        // Enable GPIOA clock


    // Enable SYSCFG clock (required for EXTI configuration)
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

    // Configure PG14 as an output for the LED
	GPIOG->MODER &= ~(GPIO_MODER_MODE14);
	GPIOG->MODER |= GPIO_MODER_MODE14_0; // Output mode

	// Configure PA0 as an input for the push button
	GPIOA->MODER &= ~GPIO_MODER_MODER0; // Input mode


	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR0_1; // Enable pull-up resistor


    // Configure PA0 for interrupt
	//SYSCFG->EXTICR[0] |= 0xF;
    SYSCFG->EXTICR[0] = SYSCFG_EXTICR1_EXTI0_PA;

   // This enable the pin PA0 for external Interrupt
   EXTI->IMR |= EXTI_IMR_MR0;

   // Falling edge is enable here for interrupt since the push button is high always since the push up and push
   // up push down register is up already
   EXTI->FTSR |= EXTI_FTSR_TR0; // Falling edge trigger


   // Enable EXTI13 interrupt and set priority
   NVIC_SetPriority(EXTI0_IRQn, 0);

   NVIC_EnableIRQ(EXTI0_IRQn);

   // Clear pending interrupt for EXTI0
   	EXTI->PR = EXTI_PR_PR0;


    while(1) {
//        GPIOG->ODR |=  GPIO_ODR_OD14;  // turn on LED  0x1 << 14
//        delayMs(500);
//        GPIOG->ODR &= ~(GPIO_ODR_OD14);  /* turn off LED */
//        delayMs(500);
    }
}

/* 16 MHz SYSCLK */
void delayMs(int n) {
    int i;
    for (; n > 0; n--)
        for (i = 0; i < 3195; i++) ;
}


void EXTI0_IRQHandler(void)
{
	 GPIOG->ODR |=  GPIO_ODR_OD14;  // turn on LED  0x1 << 14
	 delayMs(500);
	 GPIOG->ODR &= ~(GPIO_ODR_OD14);  /* turn off LED */
	 delayMs(500);

	 GPIOG->ODR |=  GPIO_ODR_OD14;  // turn on LED  0x1 << 14
	 delayMs(500);
	 GPIOG->ODR &= ~(GPIO_ODR_OD14);  /* turn off LED */
	 delayMs(500);

	 // Clear pending interrupt for EXTI0
	 EXTI->PR = EXTI_PR_PR0;
}
